# -*- coding: utf-8 -*-

UNI_LSTM = 'UNIDIRECTIONAL LSTM'
BI_LSTM = 'BIDIRECTIONAL LSTM'
SENT_FEED = 'sentences'
PARA_FEED = 'paragraphs'
W2V = 'W2V'
CHAR_LSTM = 'CHAR_LSTM'
SUFFIX = 'SUFFIX'
SUFFIX_EMBED = 'SUFFIX_EMBED'
CONCRAFT = 'CONCRAFT'
CONCRAFT_WEIGHTS = 'CONCRAFT_WEIGHTS'
NKJP = 'NKJP'
MORFEUSZ_R = 'MORFEUSZ_R'
